### ISSUE TITLE
When launch Companion it spams C2 error in chat..

### ISSUE THREAD

**Issue by Smetana5** [carsakiller/Carsas-Companion#71]
After succesfully installing carsas commands on dedicaated server (which works, you can see in video) I wanted to run Companion app, just for my when I am at work so I can see if my friends plays etc. The website somehow works, but its not working like it should. After some time it syncs and I can see informations in the companion. But cant do nothing with them, because there is some error in sending the command from companion to server (I gave owner permission to the Server user, thought it would reslove) But stills spams chat, the server gets choppy after a while like this. So I have to turn off the companion while playing. 
Would really love to resolve this issue.
I uploaded video on Google Drive (Because the video rendered at 350MB xD) video hopefully capturing all needed informations. Server view/Client view etc.
Link : https://drive.google.com/file/d/1HncffdZ_ydgYxGeF2CxbasIL-7vUvR8p/view?usp=share_link

Thank you very much, Filip. :)

**Comment by CrazyFluffyPony** [comment]
Hey @Smetana5  we just released an update for Carsas Commands through the steam workshop which should help us debugging your issue.
Please try again after you updated.

**Comment by carsakiller** [comment]
Thank you for helping out!
