### ISSUE TITLE
Add filter to map

### ISSUE THREAD

**Issue by CrazyFluffyPony** [carsakiller/Carsas-Companion#75]
So you can filter for
* player
* static vehicles
* other vehicles

**Comment by CrazyFluffyPony** [comment]
vehicle should have the field `static`, to work with the current implemented static vehicle filter option

**Comment by carsakiller** [comment]
Static *could* be useful I guess, but I think `server` would be a more useful filter. That can be achieved “easily” by only showing vehicles where the `peerID === -1`.

**Comment by CrazyFluffyPony** [comment]
> Static _could_ be useful I guess, but I think `server` would be a more useful filter. That can be achieved “easily” by only showing vehicles where the `peerID === -1`.

further improvements will be handled in #78

**Comment by CrazyFluffyPony** [comment]
done
